// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjB71OAF2sMmpM5XRR9BiNtNhgiJ4NgYE',
    appId: '1:1019474035520:web:192e50744dfa3827fa30a5',
    messagingSenderId: '1019474035520',
    projectId: 'child-immunization-tracker',
    authDomain: 'child-immunization-tracker.firebaseapp.com',
    storageBucket: 'child-immunization-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUSaDEBgXWKwSmyis7AKferJ0iccqSfs',
    appId: '1:1019474035520:android:fa5922aa8f851a2bfa30a5',
    messagingSenderId: '1019474035520',
    projectId: 'child-immunization-tracker',
    storageBucket: 'child-immunization-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAA2hr80Ik7FbAS7mQdGnGp812JZh5n4',
    appId: '1:1019474035520:ios:2294052c109663acfa30a5',
    messagingSenderId: '1019474035520',
    projectId: 'child-immunization-tracker',
    storageBucket: 'child-immunization-tracker.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAA2hr80Ik7FbAS7mQdGnGp812JZh5n4',
    appId: '1:1019474035520:ios:2294052c109663acfa30a5',
    messagingSenderId: '1019474035520',
    projectId: 'child-immunization-tracker',
    storageBucket: 'child-immunization-tracker.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjB71OAF2sMmpM5XRR9BiNtNhgiJ4NgYE',
    appId: '1:1019474035520:web:05caca790f1f782ffa30a5',
    messagingSenderId: '1019474035520',
    projectId: 'child-immunization-tracker',
    authDomain: 'child-immunization-tracker.firebaseapp.com',
    storageBucket: 'child-immunization-tracker.firebasestorage.app',
  );
}
